# This is a basic workflow to help you get started with Actions

name: develop-v2

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  # pull_request:
  #   branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-test:
    # Add "id-token" with the intended permissions
    permissions:
      contents: "read"
      id-token: "write"

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
      with:
        fetch-depth: 0
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token: 'access_token'
        workload_identity_provider: 'principalSet://iam.googleapis.com/projects/420582266371/locations/global/workloadIdentityPools/githubactions/github'
        service_account: 'githubactions@cluster-dev-home.iam.gserviceaccount.com'
        
    - name: 'Setup Gcloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - id: 'Gcloud'
      name: 'gcloud'
      run: |-
        gcloud secrets versions access "latest" --secret "my-secret"
